#themes that i like 
# merlot, architect, midnight, 
#i really like - minima, modernist, tactile

title: projbyzuri
description: zuri's project website for jobs and such|Hey I'm Zuri! This is where I'll be keeping all of my projects, and where I will document my progress and journey through comp sci! I'm also trying to make it look a little cooler so it's only boring looking right now. enjoy!
theme: minima
url: zurimckee.github.io/